### ISSUE TITLE
Краш при запуске

### ISSUE THREAD

**Issue by karina-dev** [yushman/YetAnotherTestApp#1]
java.lang.IllegalArgumentException: No injector factory bound for Class<com.example.yetanothertestapp.ui.fragment.MoviesFragment>
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:136)
        at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:93)
        at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:67)
        at com.example.yetanothertestapp.ui.fragment.MoviesFragment.onCreate(MoviesFragment.kt:40)

в методе 

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AndroidSupportInjection.inject(this)
    }

**Comment by yushman** [comment]
Исправлено, заменил Dagger на Koin
Работает:
1. Короткий тап - Тост с названием
2. Длинный тап - Добавление/Удаление в избранное и тост об этом
3. Если домотать до конца загруженной страницы - будет футер загрузка (если это не последняя страница)
4. Если при загрузке ошибка - будет футер с кнопкой перезагрузить
5. Pull-to-refresh
6. Поиск по "Избранным"
7. Если поиск пустой - экран "Пустой поиск"
8. Задержка в 1сек после ввода текста для поиска, что бы не спамить в бд
9. Пагинация
Вроде все по ТЗ
